automate:
  browser:
    default: chrome
  drivers:
    chrome:
      driver : '/.../chromedriver'
    firefox:
      driver: '/.../gueckodriver'
  scenario:
    folder: '/.../scenario'
  specs:
    folder: '/.../specs'
  logs:
    enable: false
    folder: '/.../logs'
