automate:
  browser:
    default: chrome
  drivers:
    chrome:
      driver : '/.../chromedriver'
    firefox:
      driver: '/.../gueckodriver'
  scenarioFolder: '/.../scenario'
  logs:
    enable: false
    folder: '/.../logs'
